/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Pallete: typeof import('./src/components/ui/organisms/builder/Pallete.vue')['default']
    WorkFlowEdge: typeof import('./src/components/ui/organisms/builder/WorkFlowEdge.vue')['default']
    WorkFlowNode: typeof import('./src/components/ui/organisms/builder/WorkFlowNode.vue')['default']
  }
}
