/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionEmailNode: typeof import('./src/components/ui/organisms/builder/nodes/ActionEmailNode.vue')['default']
    ActionHttpNode: typeof import('./src/components/ui/organisms/builder/nodes/ActionHttpNode.vue')['default']
    ActionSmsNode: typeof import('./src/components/ui/organisms/builder/nodes/ActionSmsNode.vue')['default']
    BaseNode: typeof import('./src/components/ui/organisms/builder/nodes/base/BaseNode.vue')['default']
    BaseNodeContent: typeof import('./src/components/ui/organisms/builder/nodes/base/BaseNodeContent.vue')['default']
    BaseNodeHandle: typeof import('./src/components/ui/organisms/builder/nodes/base/BaseNodeHandle.vue')['default']
    BaseNodeHeader: typeof import('./src/components/ui/organisms/builder/nodes/base/BaseNodeHeader.vue')['default']
    Button: typeof import('./src/components/ui/atoms/button.vue')['default']
    Canvas: typeof import('./src/components/ui/organisms/builder/Canvas.vue')['default']
    Codeditor: typeof import('./src/components/ui/atoms/codeditor.vue')['default']
    ConfigPanel: typeof import('./src/components/ui/organisms/builder/ConfigPanel.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HttpNodeConfig: typeof import('./src/components/ui/organisms/builder/config/HttpNodeConfig.vue')['default']
    Input: typeof import('./src/components/ui/atoms/input.vue')['default']
    KeyValueInput: typeof import('./src/components/ui/atoms/key-value-input.vue')['default']
    LogicDelayNode: typeof import('./src/components/ui/organisms/builder/nodes/LogicDelayNode.vue')['default']
    LogicIfElseNode: typeof import('./src/components/ui/organisms/builder/nodes/LogicIfElseNode.vue')['default']
    LogicTransformNode: typeof import('./src/components/ui/organisms/builder/nodes/LogicTransformNode.vue')['default']
    NumberInput: typeof import('./src/components/ui/atoms/number-input.vue')['default']
    Pallete: typeof import('./src/components/ui/organisms/builder/Pallete.vue')['default']
    Select: typeof import('./src/components/ui/atoms/select.vue')['default']
    Textarea: typeof import('./src/components/ui/atoms/textarea.vue')['default']
    Topbar: typeof import('./src/components/ui/organisms/builder/Topbar.vue')['default']
    TriggerManualNode: typeof import('./src/components/ui/organisms/builder/nodes/TriggerManualNode.vue')['default']
    TriggerWebhookNode: typeof import('./src/components/ui/organisms/builder/nodes/TriggerWebhookNode.vue')['default']
    WorkFlowEdge: typeof import('./src/components/ui/organisms/builder/WorkFlowEdge.vue')['default']
    WorkFlowNode: typeof import('./src/components/ui/organisms/builder/WorkFlowNode.vue')['default']
  }
}
